Repository Automattic/simplenote-electron, pull requests merged in 2018-09, with the labels that each got.

#812 Bump Electron version to 2.0.8
  lib/context-menu.jsx
  package-lock.json
  package.json
Labels: [Status] Ready to Merge

#808 Add ajv package (peer dependency of webpack)
  package-lock.json
  package.json
Labels: [Status] Ready to Merge

#813 [macOS] Put “Bring All to Front” in proper menu
  desktop/app.js
Labels: [OS] macOS, [Status] Ready to Merge

#834 Use `cheap-module-eval-source-map` for sourcemaps
  webpack.config.js
Labels: priority-high

#826 add modification timestamp to zip
  lib/utils/export/to-zip.js
Labels: OSS Citizen, enhancement

#829 Dependency audit
  package-lock.json
  package.json
Labels: priority-low

#835 Add noop as callback for fs.writeFile
  lib/app.jsx
Labels: priority-low

#849 Fix eslint errorUpdate filename in webpack config.
  webpack.config.js
Labels: [Status] Needs Review

#821 Add spellchecker (electron-spellchecker)
  Makefile
  desktop/app.js
  desktop/context-menu/context-menu-builder.js
  desktop/context-menu/index.js
  desktop/context-menu/spellcheck-handler.js
  desktop/preload.js
  electron-builder.json
  lib/app.jsx
  lib/auth/index.jsx
  lib/dialog/index.jsx
  lib/dialogs/share/index.jsx
  lib/note-info/index.jsx
  lib/search-field/index.jsx
  lib/tag-input/index.jsx
  lib/tag-list/index.jsx
  package-lock.json
  package.json
Labels: [Status] Needs Review

#859 Improve DX
  Makefile
  desktop/app.js
  desktop/env.js
  desktop/menus/view-menu.js
  misty.yml
  package-lock.json
  package.json
Labels: [Status] Needs Review

#885 Fix Appveyor builds
  appveyor.yml
Labels: [Status] Ready to Merge
