Repository Automattic/simplenote-electron, pull requests merged in 2018-12, with the labels that each got.

#1058 Configure Windows Store build with prod database
  appveyor.yml
Labels: [OS] windows, priority-high

#1042 Add support for sorting the tags list
  desktop/menus/view-menu.js
  lib/app.jsx
  lib/dialogs/settings/index.jsx
  lib/editable-list/index.jsx
  lib/flux/app-state.js
  lib/state/settings/actions.js
  lib/state/settings/reducer.js
  lib/tag-list/index.jsx
Labels: enhancement

#1088 Remove markdown in preview without triggering bug
  lib/utils/note-utils.js
  lib/utils/note-utils.test.js
  package-lock.json
  package.json
Labels: priority-high
