Repository Automattic/simplenote-electron, pull requests merged in 2018-11, with the labels that each got.

#922 Importer: Add core Simplenote format support
  lib/utils/import/README.MD
  lib/utils/import/index.js
  lib/utils/import/test.js
Labels: enhancement

#940 Add Evernote Import Parser
  lib/utils/import/evernote/index.js
  package.json
Labels: enhancement

#974 Add tests before packaging
  .circleci/config.yml
  appveyor.yml
Labels: [Status] Needs Review

#990 Update jest to fix vulnerabilities
  package-lock.json
  package.json
Labels: priority-low

#869 Improve auto updater
  .circleci/config.yml
  .gitignore
  appveyor.yml
  desktop/config-updater.json
  desktop/updater/auto-updater/index.js
  desktop/updater/index.js
  desktop/updater/lib/Updater.js
  desktop/updater/manual-updater/index.js
  package-lock.json
  package.json
Labels: [Status] Needs Review

#920 Fix appx builds
  appveyor.yml
  electron-builder-appx.json
Labels: [Status] Needs Review

#1015 Add “Debugging Console” menu item in production builds
  desktop/app.js
  desktop/menus/view-menu.js
Labels: priority-high

#989 Add :focus outline to dropzone
  lib/dialogs/import/dropzone/style.scss
Labels: accessibility

#1005 Fix padding for trash toolbar in Mac Electron
  lib/note-toolbar/style.scss
Labels: [OS] macOS, priority-low

#1031 Fix Button Styles for Navigation Drawer
  lib/navigation-bar/item/style.scss
Labels: bug

#1029 Delete AppData on uninstall
  electron-builder.json
Labels: [OS] windows
