Repository Automattic/simplenote-electron, pull requests merged in 2018-03, with the labels that each got.

#649 #555 Remove # from title on left panel
  lib/note-list.jsx
  lib/utils/note-title.js
  lib/utils/note-utils.js
Labels: OSS Citizen, [Status] Needs Author Reply, bug

#712 Update to React 16
  lib/app.jsx
  lib/auth.jsx
  lib/components/spinner.jsx
  lib/context-menu.jsx
  lib/dialog.jsx
  lib/dialogs/about.jsx
  lib/dialogs/settings.jsx
  lib/dialogs/share.jsx
  lib/editable-list.jsx
  lib/editor/css-class-wrapper.jsx
  lib/list.jsx
  lib/navigation-bar.jsx
  lib/note-content-editor.jsx
  lib/note-detail.jsx
  lib/note-editor.jsx
  lib/note-info.jsx
  lib/note-list.jsx
  lib/note-toolbar.jsx
  lib/revision-selector.jsx
  lib/search-field.jsx
  lib/tabbed-dialog.jsx
  lib/tag-field.jsx
  lib/tag-input.jsx
  lib/tag-list.jsx
  package.json
Labels: [Status] Needs Review

#720 Fix copying published note url when previewing markdown
  lib/note-detail.jsx
Labels: bug

#724 XSS Refactor: Replace `showdown-xss` with in-house sanitizer
  lib/note-detail.jsx
  lib/note-editor.jsx
  lib/utils/render-note-to-html.js
  lib/utils/sanitize-html.js
  package-lock.json
  package.json
Labels: [Status] Ready to Merge
