Repository Automattic/simplenote-electron, pull requests merged in 2018-10, with the labels that each got.

#903 Make sure that ⌃⌘F doesn't trigger Search Notes (Mac)
  lib/app.jsx
Labels: [OS] macOS

#896 Update secrets for new appveyor org
  .vscode/launch.json
  appveyor.yml
Labels: [Status] Needs Review

#973 Move shared modules to designated folder
  desktop/app.js
  electron-builder.json
  lib/dialogs/index.js
  lib/navigation-bar/index.jsx
  lib/note-toolbar-container.js
  lib/tag-email-tooltip/index.jsx
  shared/dialog-types.js
Labels: priority-high
