Repository Automattic/simplenote-electron, pull requests merged in 2019-11, with the labels that each got.

#1693 Update dependencies to latest
  RELEASE-NOTES.txt
  package-lock.json
  package.json
Labels: [status] Ready to Merge

#1692 Add Release Notes section for version 1.12.0
  RELEASE-NOTES.txt
Labels: [status] needs code review

#1702 Fixes markdown code styles
  RELEASE-NOTES.txt
  lib/note-detail/style.scss
  scss/theme.scss
Labels: [status] needs code review, [status] needs design review

#1700 Ensure that only one tab or window is open per browser
  RELEASE-NOTES.txt
  lib/boot.js
  lib/components/boot-warning/index.jsx
  lib/components/boot-warning/style.scss
  lib/utils/ensure-single-browser-tab-only.js
Labels: [status] needs code review

#1710 Add pagehide to make page unload code work on iOS and iPad
  lib/utils/ensure-single-browser-tab-only.js
Labels: [status] needs code review

#1718 Remove GitHub actions as they can no longer run
  .github/actions/deploy/Dockerfile
  .github/actions/deploy/deploy.yml
  .github/actions/deploy/entrypoint.sh
  .github/workflows/deploy.yml
Labels: [status] needs code review

#1694 Updates the menu icon
  RELEASE-NOTES.txt
  lib/icons/menu.jsx
Labels: [status] needs code review

#1720 Conditionally watch event for unload to release session lock
  lib/utils/ensure-single-browser-tab-only.js
Labels: [status] needs code review

#1723 Add script to deploy web app
  RELEASE-NOTES.txt
  bin/deploy.sh
  package.json
Labels: [status] needs code review

#1729 Merge release 1.11 into develop
  package-lock.json
  package.json
Labels: releases

#1730 Merge release 1.11 into master
  RELEASE-NOTES.txt
  lib/utils/note-utils.js
  lib/utils/note-utils.test.js
  package-lock.json
  package.json
  scss/_general.scss
Labels: releases

#1648 Search: Add tag suggestions to notes list
  RELEASE-NOTES.txt
  lib/note-list/index.jsx
  lib/note-list/style.scss
  lib/search-field/index.jsx
  lib/tag-suggestions/index.jsx
  lib/tag-suggestions/style.scss
  scss/_components.scss
  scss/theme.scss
Labels: [feature] search, [status] needs code review

#1738 Updates dependencies
  RELEASE-NOTES.txt
  package-lock.json
  package.json
Labels: [status] needs code review

#1736 Fix settings URL so that it send the correct url param to GAE
  RELEASE-NOTES.txt
  lib/dialogs/settings/panels/account.jsx
Labels: [status] needs code review

#1741 Fixes bug where window is dragged when trying to select a note revision
  RELEASE-NOTES.txt
  lib/note-detail/index.jsx
  lib/note-detail/style.scss
  lib/note-toolbar-container.js
  lib/revision-selector/index.jsx
  lib/revision-selector/style.scss
  scss/_general.scss
Labels: [status] needs code review
