Repository Automattic/simplenote-electron, pull requests merged in 2019-12, with the labels that each got.

#1759 Update Dependencies
  RELEASE-NOTES.txt
  package-lock.json
  package.json
Labels: [status] needs code review

#1767 Remove code that stops settings from scrolling on shorter screens
  RELEASE-NOTES.txt
  lib/components/tab-panels/style.scss
Labels: [status] needs code review

#1776 Notes list: Fix console error when there are no matching notes
  lib/note-list/index.jsx
Labels: [status] needs code review

#1743 Adds a Clipboard Button component
  RELEASE-NOTES.txt
  lib/components/clipboard-button/index.jsx
  lib/dialogs/settings/style.scss
  lib/dialogs/share/index.jsx
  package-lock.json
  package.json
Labels: [status] needs code review

#1779 Removes renovate config
  renovate.json
Labels: [status] needs code review

#1780 Updates the prettier command and applies prettier fixes
  .vscode/launch.json
  Makefile
  RELEASE-NOTES.txt
  electron-builder.json
  lib/app.jsx
  lib/auth/index.jsx
  lib/dialogs/settings/index.jsx
  lib/dialogs/settings/panels/display.jsx
  lib/dialogs/settings/panels/tools.jsx
  lib/flux/app-state.js
  lib/note-detail/index.jsx
  lib/note-editor/index.jsx
  lib/search-bar/index.jsx
  lib/search-field/index.jsx
  lib/tag-email-tooltip/index.jsx
  lib/tag-field/index.jsx
  lib/tag-list/index.jsx
  lib/tag-suggestions/index.jsx
  lib/utils/filter-notes.js
Labels: [status] needs code review

#1781 Fix lint command
  Makefile
Labels: [status] Ready to Merge

#1735 Updates collaborator email field validation
  RELEASE-NOTES.txt
  lib/dialogs/share/index.jsx
Labels: [status] Ready to Merge

#1784 Transition TransitionDelayEnter to React hooks
  RELEASE-NOTES.txt
  lib/components/transition-delay-enter/index.jsx
Labels: [status] needs code review

#1782 Lint Fixes
  after_sign_hook.js
  desktop/index.js
  desktop/updater/lib/Updater.js
  desktop/updater/manual-updater/index.js
  get-config.js
  lib/components/boot-warning/index.jsx
  lib/components/clipboard-button/index.jsx
  lib/context-menu.jsx
  lib/controls/checkbox/index.jsx
  lib/controls/toggle/index.jsx
  lib/dialogs/import/source-importer/executor/index.jsx
  lib/dialogs/import/source-importer/utils/test-importer.js
  lib/dialogs/radio-settings-group.jsx
  lib/dialogs/settings-group.jsx
  lib/dialogs/settings/panels/account.jsx
  lib/dialogs/toggle-settings-group.jsx
  lib/editable-list/index.jsx
  lib/editor/css-class-wrapper.jsx
  lib/note-content-editor.jsx
  lib/note-detail/index.jsx
  lib/note-detail/render-to-node.js
  lib/note-info/index.jsx
  lib/note-list/index.jsx
  lib/search-bar/index.jsx
  lib/search-field/index.jsx
  lib/state/domain/notes.js
  lib/state/domain/tags.js
  lib/tag-suggestions/index.jsx
  lib/utils/ensure-platform-support.js
  lib/utils/filter-notes.js
  lib/utils/import/evernote/test/enml-to-markdown.test.js
  lib/utils/import/index.js
  lib/utils/import/simplenote/test.js
  lib/utils/sync/activity-hooks.test.js
Labels: [status] needs code review

#1778 Update Dependencies
  package-lock.json
  package.json
Labels: [status] needs code review

#1783 Deletes the util for ensuring a single tab
  RELEASE-NOTES.txt
  lib/boot.js
  lib/utils/ensure-single-browser-tab-only.js
Labels: [status] needs code review

#1786 Deletes context-menu.js as it is unused
  lib/context-menu.jsx
Labels: [status] needs code review

#1789 Add eslint plugin for React Hooks
  .eslintrc.json
  RELEASE-NOTES.txt
  package-lock.json
  package.json
Labels: [status] needs code review

#1774 Sync note after restoration to update the state
  RELEASE-NOTES.txt
  lib/app.jsx
  lib/flux/app-state.js
  lib/revision-selector/index.jsx
Labels: [status] needs code review

#1790 Add git hooks to run formats, lints, and tests
  RELEASE-NOTES.txt
  package-lock.json
  package.json
Labels: [status] Ready to Merge

#1788 Fixes shortcut to enable Markdown preview
  RELEASE-NOTES.txt
  lib/note-editor/index.jsx
Labels: [status] Ready to Merge

#1798 Tags: Treat comma as a submit key
  RELEASE-NOTES.txt
  lib/tag-input/index.jsx
Labels: [feature] tags, [status] needs code review

#1801 Re-render immediately when system theme is changed
  RELEASE-NOTES.txt
  lib/app.jsx
  lib/app.test.js
  lib/browser-shell.jsx
Labels: [status] needs code review
