Repository Automattic/simplenote-electron, pull requests merged in 2019-09, with the labels that each got.

#1563 Another attempt at fixing white screen error
  lib/boot.js
Labels: [status] needs code review

#1580 Add Tests to Checkbox component
  CHANGELOG.md
  lib/components/checkbox/__snapshots__/test.js.snap
  lib/components/checkbox/style.scss
  lib/components/checkbox/test.js
Labels: [status] Ready to Merge

#1573 Fix: Cursors over UI elements should indicate clickable or text entry
  CHANGELOG.md
  lib/components/checkbox/style.scss
  lib/components/slider/style.scss
  lib/components/tag-chip/style.scss
  lib/dialogs/settings/style.scss
  lib/editable-list/style.scss
  lib/note-list/style.scss
  lib/tag-input/style.scss
  lib/tag-list/style.scss
  scss/_general.scss
  scss/buttons.scss
  scss/theme.scss
Labels: [status] Ready to Merge

#1582 Open new note upon creation
  RELEASE-NOTES.txt
  lib/app-layout/index.js
  lib/search-bar/index.jsx
Labels: [status] needs code review

#1591 Deps: Remove redundant `md5` library
  lib/dialogs/share/index.jsx
  package-lock.json
  package.json
Labels: [status] Ready to Merge

#1565 Update colours to color-studio.blog
  RELEASE-NOTES.txt
  lib/app-layout/style.scss
  lib/components/dev-badge/style.scss
  lib/components/progress-bar/style.scss
  lib/components/slider/style.scss
  lib/components/spinner/style.scss
  lib/components/sync-status/style.scss
  lib/components/tab-panels/style.scss
  lib/components/tag-chip/style.scss
  lib/controls/checkbox/style.scss
  lib/controls/toggle/style.scss
  lib/dialog-renderer/style.scss
  lib/dialog/style.scss
  lib/dialogs/about/style.scss
  lib/dialogs/import/dropzone/style.scss
  lib/dialogs/import/source-importer/executor/style.scss
  lib/dialogs/settings/style.scss
  lib/dialogs/share/style.scss
  lib/editable-list/style.scss
  lib/icon-button/style.scss
  lib/icons/style.scss
  lib/navigation-bar/item/style.scss
  lib/navigation-bar/style.scss
  lib/note-detail/style.scss
  lib/note-info/style.scss
  lib/note-list/style.scss
  lib/note-toolbar/style.scss
  lib/revision-selector/style.scss
  lib/search-bar/style.scss
  lib/search-field/style.scss
  lib/tag-input/style.scss
  lib/tag-list/style.scss
  package-lock.json
  package.json
  scss/_general.scss
  scss/_scrollbar.scss
  scss/_variables.scss
  scss/buttons.scss
  scss/inputs.scss
  scss/print.scss
  scss/style.scss
  scss/theme.scss
Labels: [OS] web, [status] needs code review, [status] needs design review, design, enhancement

#1594 Build: stop failing the build on eslint errors
  package-lock.json
  package.json
  webpack.config.js
Labels: [status] Ready to Merge

#1602 Fix spacing on markdown nested lists
  RELEASE-NOTES.txt
  lib/note-detail/style.scss
Labels: [status] needs code review
