Repository Automattic/simplenote-electron, pull requests merged in 2019-10, with the labels that each got.

#1603 Add deploy action
  .github/actions/deploy/Dockerfile
  .github/actions/deploy/deploy.yml
  .github/actions/deploy/entrypoint.sh
  .github/main.workflow
  .github/workflows/deploy.yml
  RELEASE-NOTES.txt
  actions/deploy-develop/README.md
  actions/deploy-develop/entrypoint.sh
  actions/deploy-master/Dockerfile
  actions/deploy-master/README.md
  actions/deploy-master/entrypoint.sh
Labels: [status] needs code review

#1596 Fix ESLint Errors
  lib/boot.js
  lib/dialogs/import/dropzone/index.jsx
  lib/simperium/bucket-store.js
  lib/simperium/index.js
  lib/simperium/local-queue-store.js
  lib/simperium/store-provider.js
  lib/utils/import/simplenote/index.js
  lib/utils/note-utils.js
  lib/utils/sync/nudge-unsynced.js
Labels: [status] needs code review

#1615 Refactor `systemTag` changes to stop directly mutating note object
  lib/flux/app-state.js
Labels: [status] Ready to Merge, debt

#1638 Refactor tag operations to stop directly mutating tag objects
  lib/state/domain/tags.js
Labels: [status] Ready to Merge

#1634 Refactor updating note content to stop directly mutating note object
  lib/app.jsx
  lib/flux/app-state.js
  lib/note-detail/index.jsx
Labels: [status] Ready to Merge

#1639 Refactor note tag operation to stop directly mutating note object
  lib/state/domain/notes.js
Labels: [status] Ready to Merge

#1627 Fix: Broken oAuth flow
  RELEASE-NOTES.txt
  lib/auth/index.jsx
Labels: [status] needs code review

#1642 Macos notarize
  .circleci/config.yml
  after_sign_hook.js
  appveyor.yml
  electron-builder.json
  package-lock.json
  package.json
  resources/macos/entitlements.mac.inherit.plist
  resources/macos/entitlements.mac.plist
  resources/macos/macPackager-patch.diff
  resources/macos/scheme-patch.diff
Labels: [feature] security, [status] Ready to Merge

#1581 Make system setting the default theme preference
  RELEASE-NOTES.txt
  lib/app.jsx
  lib/dialogs/settings-group.jsx
  lib/dialogs/settings/panels/display.jsx
  lib/state/settings/reducer.js
Labels: [status] needs code review

#1215 Add option to hide menu bar
  desktop/app.js
  lib/app.jsx
  lib/dialog-renderer/index.jsx
  lib/dialogs/settings/index.jsx
  lib/dialogs/settings/panels/display.jsx
  lib/navigation-bar/index.jsx
  lib/navigation-bar/style.scss
  lib/state/settings/actions.js
  lib/state/settings/reducer.js
Labels: [status] needs code review

#1651 Fix diff files
  resources/macos/macPackager-patch.diff
  resources/macos/scheme-patch.diff
Labels: tooling

#1652 Add release version numbers
  RELEASE-NOTES.txt
Labels: [status] needs code review

#1675 Update the link to the Release Notes in the updater config
  RELEASE-NOTES.txt
  desktop/config-updater.json
Labels: [status] needs code review

#1660 In Dev mode, open Chrome Deve Tools in detached mode
  RELEASE-NOTES.txt
  desktop/app.js
Labels: [status] needs code review

#1655 Fix to make macOS app movable on log in screen
  scss/_general.scss
Labels: [status] needs code review

#1676 Update dependencies to the latest
  RELEASE-NOTES.txt
  package-lock.json
  package.json
Labels: [status] needs code review

#1680 Fix/only run notes loaded when notes loaded
  RELEASE-NOTES.txt
  lib/flux/app-state.js
Labels: [status] needs code review

#1647 Show more than first line in note list preview
  RELEASE-NOTES.txt
  lib/utils/note-utils.js
  lib/utils/note-utils.test.js
Labels: [status] needs code review
