Repository Automattic/simplenote-electron, pull requests merged in 2019-01, with the labels that each got.

#1131 Close note after trash commands in mobile width
  lib/note-toolbar-container.js
Labels: bug

#1104 Prevent NoteList excerpts from being too short
  lib/utils/note-utils.js
  lib/utils/note-utils.test.js
Labels: priority-low

#1062 Dark Theme Tweaks
  lib/note-detail/style.scss
  scss/_variables.scss
  scss/theme.scss
Labels: enhancement
