Repository Automattic/simplenote-electron, pull requests merged in 2019-07, with the labels that each got.

#1400 Aria Label
  lib/search-field/index.jsx
Labels: [status] needs code review

#1422 Add check for local config over dev config
  .gitignore
  get-config.js
Labels: [status] needs code review

#1429 Add deploy script and vip assets
  .circleci/config.yml
  .github/main.workflow
  actions/deploy-develop/Dockerfile
  actions/deploy-develop/README.md
  actions/deploy-develop/entrypoint.sh
  vip/package.json
  vip/webapp/index.js
Labels: [status] Ready to Merge

#1402 added styles for both light and dark theme to highlight note and chan…
  lib/note-list/style.scss
  scss/_variables.scss
  scss/theme.scss
Labels: [status] needs code review, [status] needs design review

#1450 Remove Simperium link from about page
  lib/dialogs/about/index.jsx
Labels: [status] needs code review

#1451 Fix the develop build
  .github/main.workflow
  actions/deploy-develop/entrypoint.sh
  webpack.config.js
Labels: [status] needs code review

#1452 Updates dark mode note list styling
  scss/theme.scss
Labels: [status] needs code review

#1461 Fixes public path for electron
  webpack.config.js
Labels: [status] needs code review

#1459 Updates log in and sign up styling in Electron app
  CHANGELOG.md
  lib/auth/index.jsx
  lib/auth/style.scss
Labels: [status] needs code review
