Repository Automattic/simplenote-electron, pull requests merged in 2019-08, with the labels that each got.

#1510 Adds release deploy when something is merged to master
  .github/main.workflow
  actions/deploy-master/Dockerfile
  actions/deploy-master/README.md
  actions/deploy-master/entrypoint.sh
Labels: [status] needs code review

#1516 Fixes webpack bug where wrong file is requested
  webpack.config.js
Labels: [status] needs code review

#1519 Alert if browser does not support indexeddb
  lib/simperium/ghost-store.js
Labels: [status] needs copy review

#1534 Updates error copy
  lib/auth/index.jsx
Labels: [status] needs code review

#1530 Fix/webpack chunkname with hash
  webpack.config.js
Labels: [status] needs code review, tooling

#1543 Add a hash to app.js to blow out cache
  webpack.config.js
Labels: [status] needs code review

#1532 Fixes tos link in electron app
  lib/auth/index.jsx
Labels: [status] needs code review

#1547 Fix/symbol transform for ie
  babel.config.js
  lib/boot.js
  package-lock.json
  package.json
  webpack.config.js
Labels: [status] needs code review

#1557 PR Template: Update Release section to be required
  .github/PULL_REQUEST_TEMPLATE.md
Labels: tooling
