Repository Automattic/simplenote-electron, pull requests merged in 2020-01, with the labels that each got.

#1802 Update Dependencies
  RELEASE-NOTES.txt
  package-lock.json
  package.json
Labels: [status] needs code review

#1821 Update Dependencies
  RELEASE-NOTES.txt
  package-lock.json
  package.json
Labels: [status] needs code review

#1823 Fix ol numbering in markdown preview
  RELEASE-NOTES.txt
  lib/utils/sanitize-html.ts
Labels: [status] needs code review

#1822 Render unfinished lists correctly
  RELEASE-NOTES.txt
  lib/utils/render-note-to-html.ts
Labels: [status] needs code review

#1806 Sets babel compact option to false is development
  RELEASE-NOTES.txt
  babel.config.js
Labels: [status] needs code review

#1828 Filter notes: Make tag match inclusive of unicode characters
  RELEASE-NOTES.txt
  lib/utils/filter-notes.ts
Labels: [status] needs code review

#1831 Note list: Make decorator for search result highlighting case insensitive
  RELEASE-NOTES.txt
  lib/note-list/decorators.tsx
Labels: [status] needs code review

#1834 Fix tag rename functionality
  RELEASE-NOTES.txt
  lib/state/domain/tags.ts
Labels: [status] needs code review

#1837 Fix: Replace missing click handler in revision slider
  RELEASE-NOTES.txt
  lib/revision-selector/index.tsx
Labels: [status] Ready to Merge, bug

#1847 Stop erasing the copy buffer if copying empty editor selections
  RELEASE-NOTES.txt
  lib/note-content-editor.tsx
Labels: [status] Ready to Merge, enhancement

#1849 Add Types to state ui actions
  RELEASE-NOTES.txt
  lib/state/ui/actions.ts
Labels: [status] needs code review, state

#1856 Refactor: Add types to legacy Redux modules
  lib/state/action-types.ts
  lib/state/actions.ts
  lib/state/auth/actions.ts
  lib/state/auth/constants.ts
  lib/state/auth/reducer.ts
  lib/state/auth/selectors.ts
  lib/state/index.ts
  lib/state/settings/actions.ts
  lib/state/settings/reducer.ts
  lib/state/ui/actions.ts
  lib/state/ui/middleware.ts
  lib/state/ui/reducer.ts
  lib/types.ts
Labels: [status] Ready to Merge

#1848 Updates Dependencies to latest
  RELEASE-NOTES.txt
  package-lock.json
  package.json
Labels: [status] needs code review

#1867 Remove unneeded action declarations
  lib/state/action-types.ts
Labels: [status] needs code review

#1870 Move simperium connection state from flux to redux
  lib/app.tsx
  lib/components/sync-status/index.tsx
  lib/flux/app-state.ts
  lib/navigation-bar/index.tsx
  lib/state/action-types.ts
  lib/state/index.ts
  lib/state/ui/actions.ts
  lib/state/ui/reducer.ts
Labels: [status] needs code review

#1872 Remove print state and call print directly
  desktop/menus/file-menu.js
  lib/app.tsx
  lib/flux/app-state.ts
  lib/note-detail/index.tsx
  lib/state/index.ts
Labels: [status] needs code review

#1851 Refactor selected note state from flux to redux
  RELEASE-NOTES.txt
  babel.config.js
  lib/app-layout/index.tsx
  lib/app.tsx
  lib/dialogs/share/index.tsx
  lib/flux/app-state.ts
  lib/flux/test.ts
  lib/note-editor/index.tsx
  lib/note-info/index.tsx
  lib/note-list/index.tsx
  lib/note-toolbar/index.tsx
  lib/revision-selector/index.tsx
  lib/state/action-types.ts
  lib/state/index.ts
  lib/state/ui/actions.ts
  lib/state/ui/middleware.ts
  lib/state/ui/reducer.ts
  lib/types.ts
  package-lock.json
Labels: [status] needs code review, state
