Repository Automattic/simplenote-electron, pull requests merged in 2020-02, with the labels that each got.

#1871 Move unsyncednoteids state from flux to redux
  lib/app.tsx
  lib/components/sync-status/index.tsx
  lib/components/sync-status/popover.tsx
  lib/flux/app-state.ts
  lib/state/action-types.ts
  lib/state/ui/actions.ts
  lib/state/ui/reducer.ts
Labels: [status] needs code review

#1804 Use name attribute not the deprecated getter function
  desktop/menus/mac-app-menu.js
  desktop/menus/menu-items.js
  desktop/updater/lib/Updater.js
Labels: [status] needs code review

#1888 Fix keyboard shortcuts on Windows Chrome
  lib/app.tsx
  lib/note-editor/index.tsx
  lib/note-list/index.tsx
Labels: [status] needs code review

#1889 Add types and reduce function context
  lib/boot.ts
  lib/utils/is-dev-config/index.ts
  lib/utils/is-dev-config/test.ts
Labels: [status] needs code review

#1902 Move list title to redux
  lib/flux/app-state.ts
  lib/search-field/index.tsx
  lib/state/index.ts
  lib/state/ui/reducer.ts
Labels: [status] needs code review, state

#1900 Fixes background on tag edit button
  lib/tag-list/style.scss
Labels: [status] needs code review

#1866 Move editor mode to redux
  desktop/menus/file-menu.js
  lib/app.tsx
  lib/flux/app-state.ts
  lib/note-detail/index.tsx
  lib/note-editor/index.tsx
  lib/note-toolbar-container.ts
  lib/note-toolbar/index.tsx
  lib/search-bar/index.tsx
  lib/state/action-types.ts
  lib/state/index.ts
  lib/state/ui/actions.ts
  lib/state/ui/reducer.ts
  lib/types.ts
Labels: [status] needs code review, state

#1905 Tag suggestions: Matches should be case insensitive
  lib/tag-suggestions/index.tsx
  lib/tag-suggestions/test.tsx
Labels: [feature] search, [status] Ready to Merge, bug

#1894 Refactor getNoteTitles
  lib/components/sync-status/get-note-titles.ts
  lib/tag-suggestions/index.tsx
  lib/utils/filter-at-most.ts
Labels: [status] needs code review

#1881 Move Search state to redux
  lib/flux/app-state.ts
  lib/note-content-editor.tsx
  lib/note-detail/index.tsx
  lib/note-editor/index.tsx
  lib/note-list/index.tsx
  lib/search-bar/index.tsx
  lib/search-field/index.tsx
  lib/state/action-types.ts
  lib/state/index.ts
  lib/state/ui/actions.ts
  lib/state/ui/middleware.ts
  lib/state/ui/reducer.ts
  lib/tag-suggestions/index.tsx
  lib/utils/filter-notes.ts
Labels: [status] needs code review, state

#1895 Refactors closeNote to Redux
  lib/app-layout/index.tsx
  lib/app.tsx
  lib/flux/app-state.ts
  lib/note-editor/index.tsx
  lib/note-list/index.tsx
  lib/note-toolbar-container.ts
  lib/note-toolbar/index.tsx
  lib/search-bar/index.tsx
  lib/state/action-types.ts
  lib/state/ui/actions.ts
  lib/state/ui/reducer.ts
Labels: [status] needs code review, state

#1899 Moves Tag Editing state from flux to redux
  lib/flux/app-state.ts
  lib/state/action-types.ts
  lib/state/index.ts
  lib/state/ui/actions.ts
  lib/state/ui/reducer.ts
  lib/tag-list/index.tsx
Labels: [status] needs code review

#1903 Move viewing revisions logic to redux
  lib/flux/app-state.ts
  lib/note-toolbar-container.ts
  lib/note-toolbar/index.tsx
  lib/revision-selector/index.tsx
  lib/state/action-types.ts
  lib/state/index.ts
  lib/state/ui/actions.ts
  lib/state/ui/reducer.ts
Labels: [status] needs code review, state

#1901 Move showTrash from appState to Redux
  lib/flux/app-state.ts
  lib/navigation-bar/index.tsx
  lib/note-list/index.tsx
  lib/search-bar/index.tsx
  lib/state/index.ts
  lib/state/ui/reducer.ts
  lib/utils/filter-notes.ts
Labels: [status] needs code review, state

#1915 Fix revisions loading on revisions panel toggle
  lib/note-content-editor.tsx
  lib/note-toolbar/index.tsx
  lib/revision-selector/index.tsx
Labels: [status] needs code review

#1918 Add Redux Devtools enhancer to store to make extension function
  lib/state/index.ts
Labels: [status] needs code review

#1919 Move previous index store to Redux
  lib/app.tsx
  lib/flux/app-state.ts
  lib/note-toolbar-container.ts
  lib/state/action-types.ts
  lib/state/index.ts
  lib/state/ui/actions.ts
  lib/state/ui/middleware.ts
  lib/state/ui/reducer.ts
Labels: [status] needs code review
