Repository Automattic/simplenote-electron, pull requests merged in 2021-03, with the labels that each got.

#2728 Cherry-pick "Update account creation flow (#2695)"
  RELEASE-NOTES.md
  desktop/app.js
  desktop/preload.js
  lib/alternate-login-prompt/index.tsx
  lib/alternate-login-prompt/style.scss
  lib/app.tsx
  lib/auth/index.tsx
  lib/auth/style.scss
  lib/boot-with-auth.tsx
  lib/boot-without-auth.tsx
  lib/boot.ts
  lib/global.d.ts
  lib/state/action-types.ts
  lib/state/electron/middleware.ts
  lib/state/simperium/middleware.ts
  lib/state/ui/actions.ts
  lib/state/ui/reducer.ts
  lib/welcome-message.ts
  scss/_components.scss
Labels: Releases

#2732 Bump version to 2.8.0-beta1
  package-lock.json
  package.json
Labels: Releases

#2742 Merge 2.8.0 beta 2 into develop
  lib/state/ui/reducer.ts
  package-lock.json
  package.json
Labels: Releases

#2773 Explicitly treat encoded files as binaries
  .gitattributes
Labels: tooling

#2790 Merge 2.8.0 beta 3 into develop
  RELEASE-NOTES.md
  lib/auth/index.tsx
  lib/components/tag-chip/style.scss
  lib/menu-bar/index.tsx
  lib/state/ui/reducer.ts
  package-lock.json
  package.json
Labels: Releases

#2793 Merge finalized release 2.8.0 into develop
  package-lock.json
  package.json
Labels: Releases

#2795 Bump version to 2.9.0-beta1
  package-lock.json
  package.json
Labels: Releases

#2815 Fix: Add max height to dialog's content to prevent cut off
  lib/dialog/style.scss
Labels: bug

#2816 Fix: Add overflow to changes list section of unsynchronized confirmation dialog
  lib/dialogs/unsynchronized/style.scss
Labels: bug
