Repository Automattic/simplenote-electron, pull requests merged in 2021-07, with the labels that each got.

#2946 Fix the font stack outside of the editor
  scss/_variables.scss
Labels: [status] needs design review

#2954 Merge 2.14.0 to develop
  package-lock.json
  package.json
Labels: Releases

#2964 Merge 2.15.0 final to develop
  package-lock.json
  package.json
Labels: Releases

#2965 Update Windows Tile Icons
  resources/appx/Square150x150Logo.png
  resources/appx/Wide310x150Logo.png
Labels: enhancement
