Repository Automattic/simplenote-electron, pull requests merged in 2021-04, with the labels that each got.

#2821 Bump version 2.9.0 🚀
  RELEASE-NOTES.md
  package-lock.json
  package.json
Labels: Releases

#2829 Fix: extra blank space rendering in note preview component
  lib/components/note-preview/index.tsx
  lib/components/note-preview/style.scss
  scss/_components.scss
Labels: bug

#2834 Fix: Remove fixed height from tab panels
  lib/components/tab-panels/style.scss
Labels: bug

#2843 Fix: Set checkbox component `isStandard` prop optional
  lib/controls/checkbox/index.tsx
Labels: bug

#2819 Fix: Normalize line break when exporting notes
  lib/utils/export/export-notes.ts
  lib/utils/export/normalize-line-break.ts
  lib/utils/export/test/normalize-line-breaks.ts
  lib/utils/export/to-zip.ts
Labels: bug

#2852 Test Checklist: Adding headers and more consistency with other platforms
  TESTING-CHECKLIST.md
Labels: [feature] checklist

#2854 Bump version to 2.10.0-beta1
  package-lock.json
  package.json
Labels: Releases

#2817 Add note's tags to history screen
  lib/app-layout/index.tsx
  lib/components/note-preview/index.tsx
  lib/components/tag-chip/__snapshots__/test.tsx.snap
  lib/components/tag-chip/index.tsx
  lib/components/tag-chip/style.scss
  lib/components/tag-chip/test.tsx
  lib/note-revisions/index.tsx
  lib/note-revisions/style.scss
  lib/revision-selector/index.tsx
  lib/revision-selector/style.scss
  lib/state/action-types.ts
  lib/state/data/middleware.ts
  lib/state/data/reducer.ts
  lib/state/selectors.ts
  lib/state/simperium/middleware.ts
  lib/state/ui/actions.ts
  lib/state/ui/reducer.ts
  lib/tag-field/index.tsx
  scss/_components.scss
Labels: [feature] history, enhancement

#2869 Added a `setup` test, asking to sign up using mixed-capitalization
  TESTING-CHECKLIST.md
Labels: [feature] checklist
